### ISSUE TITLE
Set Up Basic CI

### ISSUE THREAD

**Issue by Xuanwo** [pcwalton/cxx-async#7]
Let's implement basic CI to ensure we don't inadvertently break things for users.

CI should include:

- `cargo format`
- `cargo build` (both gcc & clang)
- `cargo clippy`
- `cargo test` (make sure examples can pass)

## Tasks

- [x] Build and test `examples/folly`: https://github.com/pcwalton/cxx-async/pull/10

**Comment by Xuanwo** [comment]
It appears that we need to compile the folly first. @PragmaTwice, do you have any suggestions?

**Comment by devillove084** [comment]
In the process of observing and learning cppcoro related libraries, I found that the original author did not plan to continue maintaining this repository, but there are many forks. @PragmaTwice Do you have any good suggestions? After further understanding and digging, I will give here which fork branch is used to ensure that everyone can understand which specific version is used. ：）

**Comment by Xuanwo** [comment]
> In the process of observing and learning cppcoro related libraries, I found that the original author did not plan to continue maintaining this repository, but there are many forks. @PragmaTwice Do you have any good suggestions? After further understanding and digging, I will give here which fork branch is used to ensure that everyone can understand which specific version is used. ：）

Thank you for doing research for this. Let's move this part out of this issue.
